version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
    networks:
      - internal
    user: "1000:1000" # Запуск от непривилегированного пользователя


  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  db_data:
  static_data:


networks:
  internal:
    driver: bridge
